[ "$_CONF_SECRETS_OVERWRITE_EXISTING" ] && _PASS_OPTIONS="$_PASS_OPTIONS -f"
[ "$_CONF_SECRETS_PASS_NO_SYMBOLS" ] && _PASS_OPTIONS="$_PASS_OPTIONS --no-symbols"

pass generate $_PASS_OPTIONS $_SECRET_KEY $_OPTN_PASSWORD_LENGTH && pass git push
